### ISSUE TITLE
now dev: Unable to import module 'now__launcher'

### ISSUE THREAD

**Issue by homerjam** [zeit/now-cli#2075]
```
Error: Unable to import module 'now__launcher'
    at getHandler (/Users/jameshomer/Library/Caches/co.zeit.fun/runtimes/nodejs/bootstrap.js:155:19)
    at /Users/jameshomer/Library/Caches/co.zeit.fun/runtimes/nodejs/bootstrap.js:37:23
    at Generator.next (<anonymous>)
    at /Users/jameshomer/Library/Caches/co.zeit.fun/runtimes/nodejs/bootstrap.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jameshomer/Library/Caches/co.zeit.fun/runtimes/nodejs/bootstrap.js:3:12)
    at start (/Users/jameshomer/Library/Caches/co.zeit.fun/runtimes/nodejs/bootstrap.js:34:12)
    at Object.<anonymous> (/Users/jameshomer/Library/Caches/co.zeit.fun/runtimes/nodejs/bootstrap.js:19:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
^C> Stopping `now dev` server
```

**Comment by homerjam** [comment]
This was happening because some required files weren't included in the build. Is it possible to improve the warning?
